version: '3.8'
services:
  postgre:
    image: postgres:13.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRESQL_DB_PASSWORD}
      POSTGRES_DB: dej
    volumes:
      - ./database/volumes:/var/lib/postgresql/data
    ports:
      - 5432:5432
    network_mode: bridge